### ISSUE TITLE
driver compiled with DJGPP and stubbed with CWSDPR0 (release 5)

### ISSUE THREAD

**Issue by mcluskyism** [Baron-von-Riedesel/Jemm#13]
Hello, sorry for bothering, but I get a crash while loading the Paragon DOS IFS driver.
With the previous 5.79 release, all is working as expected with these lines atop CONFIG.SYS:

- **DEVICE=MOVEXBDA.EXE**
- **DEVICE=JEMMEX.EXE FRAME=A000 I=B000-B7FF I=CF00-DBFF I=E400-E7FF MAX=32M**

But if I switch to the newest 5.80, with this line:

- **DEVICE=JEMMEX.EXE FRAME=A000 I=B000-B7FF I=CF00-DBFF I=E400-E7FF MAX=32M MOVEXBDA**

(and is the same with **DEVICE=JEMMEXL.EXE** etc.) the driver crashes at launch.
I suppose the crash occours while the driver (ndos.exe) tries to load the stubbed CWSDPR0.
As per attached image, unfortunately I'm not able to debug Jemm's error code by myself.
![20210707_013509](https://user-images.githubusercontent.com/5121242/124679050-0db73980-dec4-11eb-8038-2e358cb5526c.jpg)

If you need more details, feel free to ask.

Thank you,

Federico

**Comment by mcluskyism** [comment]
Hello, I did a test.
I dropped CWSDPR0.EXE and used instead your HX extender, loading it resident via `HDPMI32 -r`
Then, when I launch the `ndos.exe` driver:

- with Jemmex v5.79 no crashes and all work as expected again
- with Jemmex v5.80 the crash is slightly different, I still get the _PCI System Error_ etcetera but Jemmex doesn't crash and the rest of the system goes on, but then unfortunately the Paragon DOS IFS driver cease to work and I lose the drive letter assigment on the NTFS hard disk partition.

Dunno why, but surely the bug lies under the Paragon driver

**Comment by Baron-von-Riedesel** [comment]
Please note that line "DEVICE=MOVEXBDA.EXE" and jemmex option MOVEXBDA behave differently:

DEVICE=MOVEXBDA.EXE moves the XBDA to low conventional memory; jemmex option MOVEXBDA moves the XBDA to  upper memory.

Hence the first thing to try is to *remove* option MOVEXBDA from the jemmex device driver.

**Comment by mcluskyism** [comment]
Hi Andreas, first of all, thanks for the clarification.
I can close the issue, because with these lines in `config.sys`

- DEVICE=MOVEXBDA.EXE
- DEVICE=JEMMEX.EXE FRAME=A000 I=B000-B7FF I=CF00-DBFF I=E400-E7FF MAX=32M

the newest Jemmex works exactly as the previuos, no errors at all while loading the Paragon driver.
So, thanks again for your answer, work, time and patience.
My best

Federico
