### ISSUE TITLE
JEMMEX crashes with 'NOEMS'

### ISSUE THREAD

**Issue by prosper00** [Baron-von-Riedesel/Jemm#14]
real hardware: Celeron 266 w/48M SDRAM; DOS 7.1; PCI voodoo3 2000; audioPCI (SB64V); 3com 3c509b (no boot rom).

Booting with 'DEVICE=JEMMEX.EXE' works great, but 'DEVICE=JEMMEX.EXE NOEMS' generates pages of quickly scrolling errors - I can make out the phrase 'division overflow', I think - when this line is loaded during boot. I do have a Ensoniq audioPCI (SB64V) installed, but the 'SB' parameter makes no difference either way. Other than the boot menu, this line is the first one in config.sys. Have tried messing with the 'pnp OS' setting in BIOS, and clearing settings - with no change.

**Comment by Baron-von-Riedesel** [comment]
I can only guess what the problem may be. The NOEMS parameter should increase the memory range for UMBs - and this is what causes the problem. So you'll have to experiment with the X= parameter.

For example, start with

DEVICE=JEMMEX.EXE NOEMS X=E000-EFFF

and increase the region up to A000-EFFF until the error disappears.

**Comment by prosper00** [comment]
Oh, excellent - that gives me a place to start. Thanks, I'll play with it
