### ISSUE TITLE
Ideas for running "The Elder Scrolls: Arena" with JEMMEX

### ISSUE THREAD

**Issue by vanfanel** [Baron-von-Riedesel/Jemm#16]
Hi there

I just discovered that JEMMEX offers superior compatibility vs QEMM, etc

So I was trying to run "The Elder Scrolls: Arena" with it on my Vortex86-based mini computer (Tinyllama2: https://github.com/eivindbohler/tinyllama2)

The game needs EMS.

This is how I have my CONFIG.SYS and AUTOEXEC.BAT (DOS 6.22 here for max compatibility!):

CONFIG.SYS
```
[MENU]
MENUITEM=EMS, XMS and EMS + drivers
MENUITEM=NOEMS, XMS ONLY + drivers

[EMS]

DOS=HIGH
DEVICE=C:\JEMMEX.EXE X=TEST X2MAX=8192 MAX=8192
SHELL=C:\COMMAND.COM /E:2048 /P

[NOEMS]

DOS=HIGH
DEVICE=C:\JEMMEX.EXE X=TEST X2MAX=8192 MAX=8192 NOEMS
SHELL=C:\COMMAND.COM /E:2048 /P

```
AUTOEXEC.BAT

```
@ECHO OFF
PATH=C:\DOS
SET DIRCMD=/A/OGN/P
SET BLASTER=A220 I7 D1 P330 T4
PROMPT $P$G

MODE CON RATE=32 DELAY=1

C:\UNISOUND\UNISOUND.COM /V90 /VW90 /VF90 /VL90 /VP90 /VC0 /VM0

ECHO.

```

However, if I boot with EMS, Arena simply goes back to the C:> prompt, no errors, nothing.

Any ideas about options or parameters for JEMMEX to get it going, please?

**Comment by Baron-von-Riedesel** [comment]
> Any ideas about options or parameters for JEMMEX to get it going, please?

I don't have that game, so cannot try by myself. You  might try MAX=32768 to offer 32 MB EMS, also X=C000-FFFF to ensure no UMB is supplied, and MAXEXT=64M to restrict XMS to 64 MB.

**Comment by vanfanel** [comment]
@Baron-von-Riedesel Thanks for these ideas! I tried all three parameters.
With X=C000-FFFF, the game says "Not enough EMS available..." and exits immediately.
The other two simply don't make any difference.

The game is freeware, officially published by Bethesda now.
You can get it easily (and LEGALLY) here:
https://gamesnostalgia.com/download/elder-scrolls-arena/1895

**Comment by Baron-von-Riedesel** [comment]
I tried it - and found no real problems.

I used MS-DOS 7.1 ( Win98SE ) and JemmEx:

DEVICE=C:\DIV\JEMMEX.EXE MAX=32M MIN=48 I=B000-B7FF I=TEST

First, I launched a.exe - the game started, without sound.
Second, I run install.exe, selecting SB16 for sound and music.
For the third try, VSBHDA ( a SBEMU clone ) and CTMOUSE was installed; then ARENA.BAT launched - the game started, with sound and mouse this time, no apparent problems so far.

**Comment by vanfanel** [comment]
Thanks for more ideas! I have both MS-DOS 6.22 and FREEDOS installs, but not MS-DOS 7.1.
Do you think MS-DOS 7.1 would make any difference? Can you try FREEDOS instead, please?

**Comment by Baron-von-Riedesel** [comment]
> Do you think MS-DOS 7.1 would make any difference?

Very unlikely.

> Can you try FREEDOS instead, please?

Perhaps, if I find a USB stick with FreeDOS - might take some time, though ...

**Comment by vanfanel** [comment]
I am trying to replicate your configuration (instead of making you replicate mine... I don't want to was your time).

I installed MS-DOS 7.1 from CD image, but upon boot I see:
"EMM386 has detected error #01 in an application at memory address C95E:3FB5.." etc
This is on a TinyLlama v2 (https://www.vogons.org/viewtopic.php?t=84880)
Do you know what could be wrong with DOS 7.1 on this machine? I see you are using DOS 7.1 on an even more advanced machine...

**Comment by vanfanel** [comment]
I have installed MS-DOS 7.1 to try to replicate your configuration on the TinyLlama, and tried to load JEMMEX with it (latest available release in this repository), but I get this:

![repo3](https://github.com/Baron-von-Riedesel/Jemm/assets/837585/c5ae98a2-b1bf-430a-b6f2-f953e7aa7730)

**Comment by Baron-von-Riedesel** [comment]
If JemmEx displays "JemmEx loaded", it has loaded fine and the crash is likely to happen with some driver loaded into an UMB.

To "debug", avoid loading JemmEx in config.sys ( press Shift-F5 in the menu ) and instead load it from the command line, with "JemmEx load /v".

**Comment by vanfanel** [comment]
> To "debug", avoid loading JemmEx in config.sys ( press Shift-F5 in the menu ) and instead load it from the command line, with "JemmEx load /v".

Great, thanks.
I found out that the line causing the error is

`DOS=HIGH,UMB`

...which I have just after
`DEVICE=C:\DIV\JEMMEX.EXE MAX=32M MIN=48 I=B000-B7FF I=TEST`

**Comment by vanfanel** [comment]
After removing the `DOS=HIGH,UMB`, I can boot the system with JEMMEX, and I see this:
```

Jemmex v5.85 [02/11/23]
System memory found at ec00-efff, region might be in use
Using page frame dc00
Jemmex loaded
```

...But running Arena's `a.exe`, the game returns immediately to the DOS prompt and the system hangs.

**Comment by Baron-von-Riedesel** [comment]
> After removing the DOS=HIGH,UMB

This makes DOS load in conventional memory, reducing that kind of mem to ~ 500 kB. Nevertheless, I also tried that ( MEM.EXE reports 498 kB free mem ), and a.exe still starts the game.

The problem might be your BIOS - perhaps you should run MEMSTAT, supplied with Jemm, to see what regions in the first MB are marked as "reserved"...

**Comment by vanfanel** [comment]
This is what MEMSTAT says on my system (the Tinyllama v2). What do you think?
I don't know how to interpret this, I see many reserved areas. Does that mean I should somehow exclude them in JEMMEX?

![repo8](https://github.com/Baron-von-Riedesel/Jemm/assets/837585/628d4096-55bc-40dc-8d2a-3b66a10ccc3e)

**Comment by Baron-von-Riedesel** [comment]
> Does that mean I should somehow exclude them in JEMMEX?

No. Only the first MB is interesting here. The BIOS tells that region F0000-FFFFF is reserved. For Jemmex, this means that region  C0000-EFFFF may be potentially used for UMBs and the EMS page frame. It scans that region to exclude ROMS ( usually finding the VGA ROM at C0000 ) and RAM ( displaying a warning and ignore such regions ). IOW, Jemm relies on the BIOS that it reports ALL reserved regions in the first MB - if the BIOS doesn't do that exactly, errors like yours  are likely to occur. In that case, you'll have to manually exclude the "missing" reserved regions ( using the X= option ).

**Comment by vanfanel** [comment]
@Baron-von-Riedesel Ah! So this is a BIOS problem, it seems...
The TinyLlama v2 BIOS is in development. Can you tell me what the problem is so I can tell the BIOS author?

Also, what areas should I exclude in JEMMEX X=... exactly? Or is a BIOS fix needed here even with X=...?

**Comment by Baron-von-Riedesel** [comment]
> Also, what areas should I exclude in JEMMEX X=... exactly?

I don't know ( it's actually a guess only ). You'll have to try on your own. Perhaps start with X=E000-EFFF...

**Comment by vanfanel** [comment]
That doesn't work. What would be the progression?

**Comment by eivindbohler** [comment]
Hey guys, I'm the maker of the TinyLlama. I am however, not the "author" of its BIOS in the traditional sense. I've taken the Coreboot/SeaBIOS version modified by DMP back in 2013 for the Vortex86EX CPU and enhanced it slightly. Haven't touched any memory mapping.
I took a look at a detailed debug boot log now, and it includes these lines:
```
Space available for UMB: c8000-ee000, f0000-f31d0
Returned 262144 bytes of ZoneHigh
e820 map has 7 items:
  0: 0000000000000000 - 000000000009fc00 = 1 RAM
  1: 000000000009fc00 - 00000000000a0000 = 2 RESERVED
  2: 00000000000f0000 - 0000000000100000 = 2 RESERVED
  3: 0000000000100000 - 0000000007cc0000 = 1 RAM
  4: 0000000007cc0000 - 0000000007f90000 = 2 RESERVED
  5: 0000000007f90000 - 0000000007fe0000 = 1 RAM
  6: 0000000007fe0000 - 0000000008000000 = 2 RESERVED
```
Looks like the e820 map is somewhat lacking, but the "space available for UMB" line might be of interest? Try excluding the areas outside of `c8000-ee000` perhaps?

**Comment by vanfanel** [comment]
@eivindbohler Thanks for chiming in!
Do you mean leaving c8000-ee000 only as UMB available to JEMMEX?
The problem is that JEMMEX doesn't seem to provide an option to use a range only...
Shouldn't it be made on the BIOS?

**Comment by eivindbohler** [comment]
Yeah, ideally every reserved area should be included in the e820 map, but what I meant was try to manually exclude the areas around that "space available for UMB" that aren't already in the map: `X=A000-C800 X=EE00-F000`

**Comment by vanfanel** [comment]
Tried passing `X=A000-C800 X=EE00-F000` to JEMMEX, but no difference.

**Comment by vanfanel** [comment]
@Baron-von-Riedesel Are multime X parameters supported?

**Comment by Baron-von-Riedesel** [comment]
> Are multiple X parameters supported?

Why don't you just try it out? You won't cause any damage. You might also try option NORAM, which causes Jemm not to provide any UMBs ( but it will still search a suitable EMS page frame ).

**Comment by vanfanel** [comment]
As I said earlier, I already tried `X=A000-C800 X=EE00-F000`, and also I have just tried `NORAM`, but it makes no difference: Arena exits immediately with "DIVIDE ERROR".

I have the same configuration as you do: DOS 7.1 and JEMMEX.
Also, I have the exact same copy or Arena that you have.
There's something with the Tinyllama that prevernts the game to run on DOS 7.1 / 6.22 (On FreeDOS, the game boots but then hangs after the character creation screen: it doesn't get to the actual gameplay).

**Comment by vanfanel** [comment]
@eivindbohler I have gathered more information on the TinyLlama memory map using Checkit, please take a look:

![checkit1](https://github.com/Baron-von-Riedesel/Jemm/assets/837585/21b63c82-33de-47c0-a9af-2b5da5b4835c)
![checkit2](https://github.com/Baron-von-Riedesel/Jemm/assets/837585/b94fe215-fd31-467a-9838-29564931dff2)

Do you think some of those areas should be excluded from Jemmex memory management manually?

Also, there used to be options to manage IRQs in the BIOS: what did those do? Game-breaking bugs could be related to that.

**Comment by SenhorFlibble** [comment]
I've had a similar problem, and "kind of" found the solution.

Recently I installed FreeDOS in 86Box, which I configured to emulate a 486DX2 PC, and tried to run the freeware floppy version 1.06 of _Arena_ that Bethesda distributed a while ago. But the FreeDOS preset that boots JEMM386 with EMS support would result in the game hanging with a black screen whenever I tried to enter the first dungeon or load a saved game (although the main menu and character generation worked fine). I tried rolling back to the old FreeDOS EMM386 from 2006, but to no avail.

Then I decided to try the _Arena_ CD version 1.07 (also freeware, [available from GOG](https://www.gog.com/en/game/the_elder_scrolls_arena)), and it worked just fine in FreeDOS with the same JEMM386 preset. So I guess the solution to running _Arena_ under FreeDOS and/or with JEMM(EX) is to use this version, not the floppy one.

**Comment by SenhorFlibble** [comment]
Looks like I've been a bit too hasty with my conclusions.

Version 1.07 works just fine at the first glance; I finished the first dungeon, got to a town, and I can successfully enter buildings and exit the town gate to explore the wilderness. However, when I try to fast travel, the game just hangs. It may continue playing the ambient tune, but there's either a black or a white screen where normally it should play the fast travel animation.

Any ideas what may cause this, and how to solve it? JIC, here's the FreeDOS preset that I use to run _Arena_:
`DEVICE=C:\FreeDOS\BIN\HIMEMX.EXE`
`DEVICE=C:\FreeDOS\BIN\JEMM386.EXE X=TEST NOVME NOINVLPG`

**Comment by vanfanel** [comment]
@SenhorFlibble Did you try to run the game on MS-DOS (any version) instead of FreeDOS?

I'm doing:
`DEVICE=C:\DIV\JEMMEX.EXE MAX=32M MIN=48 I=B000-B7FF I=TEST`
just as you and @Baron-von-Riedesel both suggested, but the game goes back to DOS immediately, hanging my keyboard in the process.

MS-DOS seems to be more compatible with some games than FreeDOS (Realms of Arkania 2, for example), so I think it's a better option for DOS games.

**Comment by vanfanel** [comment]
@Baron-von-Riedesel The game runs with QEMM, doing this in config.sys:
`DEVICE=C:\QEMM\QEMM386.SYS RAM BE:N RF`

The key is using the `RAM` parameter: without that, the game crashes the same as in JEMMEX.
So, maybe JEMMEX could mimic QEMM to let this game work?

I have QEMM of course, but I'd prefer JEMMEX to be my choice since it's free and opensource :)

**Comment by Baron-von-Riedesel** [comment]
But isn't the RAM option just there to tell Qemm that it is to provide UMBs? That's at least the meaning of this parameter in MS Emm386.

**Comment by Baron-von-Riedesel** [comment]
Also, I tried Ultima Underworld I and II ( found a CD that contains both games ). Both work with Jemmex - however, only UW I has sound, UW II is silent. But this is very likely no Jemm issue, instead might be a VSBHDA incompatibility.

**Comment by vanfanel** [comment]
@Baron-von-Riedesel That's specially interesting.

Both TES:Arena and UW only seem to work with QEMM on the Tinyllama, but they work with JEMMEX on your computer.
Do you know what could that mean? If it's not a JEMMEX problem, what could be wrong with the TinyLlama? What does QEMM do with memory that JEMMEX does not?

**Comment by Baron-von-Riedesel** [comment]
> If it's not a JEMMEX problem, what could be wrong with the TinyLlama?

I don't know.

The best settings of JemmEx for late 80s/early 90s DOS real-mode games using EMS are:

DEVICE=JEMMEX.EXE MAXEXT=14M NODYN MIN=7M I=B000-B7FF

MAXEXT limits XMS to 14MB - so it's ensured that all memory is below the 16MB barrier.
NODYN & MIN makes JemmEx allocate MIN memory for EMS at startup.

Result: a machine with 7 MB EMS and 7 MB XMS, all addresses 24-bit, compatible with ISA DMA.

**Comment by vanfanel** [comment]
@Baron-von-Riedesel Ok, thanks. I tried `DEVICE=JEMMEX.EXE MAXEXT=14M NODYN MIN=7M I=B000-B7FF` and I get this on boot:

```
System memory found at ec00-efff, region might be in use
Using page frame dc00
```

Could it have to do with the incompatibilities I am seeing on this Vortex86 SOM?
For example, Lemmings 2 should work too but it crashes:
![jemmex_crash_lem2](https://github.com/Baron-von-Riedesel/Jemm/assets/837585/171a4df9-103d-492c-83af-b6a695d23126)

**Comment by Baron-von-Riedesel** [comment]
Lemmings 2 doesn't work on my machines. At best it "hangs", and the debugger shows it loops while accessing the disk with int 25h - I guess some sort of copy protection... using l2-fix doesn't help.

**Comment by vanfanel** [comment]
> Lemmings 2 doesn't work on my machines. At best it "hangs", and the debugger shows it loops while accessing the disk with int 25h - I guess some sort of copy protection... using l2-fix doesn't help.

What machines have you tested JEMMEX+Lemmings 2 on?
That game sure worked on Pentium-class machines back in the 90's.

**Comment by Baron-von-Riedesel** [comment]
> What machines have you tested JEMMEX+Lemmings 2 on?

AMD Ryzen 2 and Intel I5 Gen 3.

> Also, does it also hang in the "Sound Initializing" message for you?

No, I tested without sound. It simply hangs after reporting how much memory is free.

**Comment by vanfanel** [comment]
> However, I can run the game with sound by launching DosBox under HX DOS extender...

Do you mean you emulate DOS on DOS to run the game?

**Comment by vanfanel** [comment]
Also, Lemmings 2 seems unbreakable under DosBOX!
Setting a Pentium class CPU, 80000 cycles, 128MB of RAM, you name it: the game ALWAYS works. Doesn't seem so picky about hardware...

**Comment by Baron-von-Riedesel** [comment]
> Any idea on how to know what memory areas should be excluded on other systems?

Well, I know what Jemm does:

- First, it calls INT 15h, AX=E820h. If this function doesn't fail, it will tell the memory manager, what areas are "reserved".
- Then it scans the upper region C000-F7FF for ROMs - usually it finds at least the VGA ROM, perhaps also a Network card ROM.
- Finally, it tests the remaining region if it is writeable - if yes, it's also excluded ( and a warning displayed ).

**Comment by vanfanel** [comment]
@Baron-von-Riedesel So, if I theorize that `INT 15h, AX=E820h` is "broken" or doesn't return correct information on the Vertex86 SOM:
-Is there a way/tool to be sure or rule out incorrect `INT 15h, AX=E820h` ?
-Is there an alternative way to find out areas that should be excluded?

**Comment by Baron-von-Riedesel** [comment]
> Is there a way/tool to be sure or rule out incorrect INT 15h, AX=E820h ?

There's the MEMSTAT.EXE tool contained in the Jemm package.

**Comment by vanfanel** [comment]
> > Is there a way/tool to be sure or rule out incorrect INT 15h, AX=E820h ?
> 
> There's the MEMSTAT.EXE tool contained in the Jemm package.

Ok, I ran MEMSTAT.EXE and I got this:

```
conventional memory (Int 12h): 639 kB
XBDA at segment 9fc0, size 1 kB
Int 15h, ah=88h, extended memory: 0 kB
Int 15h, ax=E801h:
ext. memory below 16 MB: 15360 (0x3c00) KB
ext. memory above 16 MB: 1790 64 KB blocks = 111 MB [1000000-7fdffff]
Int 15h, eax=E820h:
 address range          size       type 
----------------------------------------------------
000000000-00009fbff      9fc00  1 (available)
00009fc00-00009ffff        400  2 (reserved)
0000f0000-0000fffff      10000  2 (reserved)
000100000-007cbffff    7bc0000  1 (available)
007cc0000-007f8ffff     2d0000  2 (reserved)
007f90000-007fdffff      50000  1 (available)
007fe0000-007ffffff      20000  2 (reserved)
----------------------------------------------------
available: 124 MB, ACPI: 0 kB, rsvd: 3 MB, total: 127 MB

```
I don't quite know how to interpret that information: Should I explicitly exclude (X=...) any regions on this machine with JEMM/EMM386 by looking at that?

Also, I disabled sound, and with JEMM/EMM386 loaded Lemmings 2 does this:

https://github.com/Baron-von-Riedesel/Jemm/assets/837585/6b866193-d5dd-49ce-97a0-61181c97c662

Without JEMM/EMM386, it loads fine.

So, enabling EMS seems to breaks Lemmings 2 graphics... I theorize EMS is overlapping with graphics memory on this system, does that make any sense?

**Comment by Baron-von-Riedesel** [comment]
>  Should I explicitly exclude (X=...) any regions on this machine with 

No, JemmEx will exclude region F0000-FFFFF automatically.

> I theorize EMS is overlapping with graphics memory on this system, does that make any sense?

No, JemmEx will never automatically put the page frame into region A0000-BFFFF. Btw, launching JemmEx from the cmdline will tell you the address of the 64kB page frame.

**Comment by vanfanel** [comment]
@Baron-von-Riedesel Yes, it says:

```
System memory found at ec00-efff, region might be in use
Using page frame dc00
Jemmex loaded
```

I'm out of ideas about Lemmings2+EMS on this system :(

**Comment by Baron-von-Riedesel** [comment]
Ok, I think we can close this - IMO the problems with Lemmings2 are not specific to Jemm.
For the record: 
1. Lemmings2 does a direct sector read ( Int 25h ), expecting drive C: to be a FAT16 partition
2. If Soundblaster is selected as sound device in v86 mode, an exception 0D occurs in Jemm/Qemm ( MS Emm386 hangs ). It's due to a word write access at offset 0xFFFF, something not allowed in true v86 mode ( no problem for DosBox, apparently ).

**Comment by vanfanel** [comment]
> Ok, I think we can close this - IMO the problems with Lemmings2 are not specific to Jemm. For the record:
> 
>     1. Lemmings2 does a direct sector read ( Int 25h ), expecting drive C: to be a FAT16 partition
> 
>     2. If Soundblaster is selected as sound device in v86 mode, an exception 0D occurs in Jemm/Qemm ( MS Emm386 hangs ). It's due to a word write access at offset 0xFFFF, something not allowed in true v86 mode ( no problem for DosBox, apparently ).

Hmm.. Maybe the Lemmings 2 executable could be edited with an hex editor to remove the word write access at offset 0xFFFF then??
