### ISSUE TITLE
JemmEx crashes on load.

### ISSUE THREAD

**Issue by oerg866** [Baron-von-Riedesel/Jemm#17]
Hello,

I have the following system:

- EPoX PP6-NB Socket 8 Motherboard
- Intel 440FX chipset 
- Pentium Pro @ 233MHz
- 160 MB RAM
- Adaptec 39160 Ultra160 PCI SCSI Adapter
- Seagate Cheetah 137GB SCSI disk
- Nvidia Riva TNT2 M64 PCI 
- 3dfx Voodoo
- Guillemot Maxi Sound 64 Home Studio (SC-8500)

Using DOS 7.10 (from Windows 98), Jemmex freezes more often than not (sometimes, very very rarely, it works).

Config.sys snippet:

```
DOS=NOAUTO
DOS=HIGH,UMB
FILES=80
BUFFERS=10
DEVICE=C:\DOS\JEMM\JEMMEX.EXE NOEMS
```

All I see is:

```
JemmEx v5.83 [12/04/22]
JemmEx loaded
```

If I reboot I often see:

```
JemmEx v5.83 [12/04/22]
Error: No supported A20 method detected
```

EMM386 works fine.

Is there any way for me to debug this?

**Comment by Baron-von-Riedesel** [comment]
> Is there any way for me to debug this?

- load jemmex from the command line.
- use the /V option when loading
- if you're experienced, you can download the source and activate debug displays for the INIT stage.
