### ISSUE TITLE
Realms of Arkania 2: Startrail 

### ISSUE THREAD

**Issue by vanfanel** [Baron-von-Riedesel/Jemm#18]
Hi there,

No matter what JEMMEX options I try, this game always crashed with a JEMMEX EXCEPTION error on every machine where I try to run it.

So has somebody got it to work with JEMMEX?

**Comment by Baron-von-Riedesel** [comment]
Don't have that game, so cannot try by myself. Try QEMM or 386MAX!

**Comment by vanfanel** [comment]
Hello @Baron-von-Riedesel 

This is what I get with JEMMEX, in case you can give me any hints:
![photo_2023-07-30_15-50-59](https://github.com/Baron-von-Riedesel/Jemm/assets/837585/d5e3bc35-2e49-4083-8d28-21fa76c30b29)

What's exception 06? Does it ring any bells?

**Comment by Baron-von-Riedesel** [comment]
> What's exception 06? Does it ring any bells?

Well, it's an "invalid opcode" exception. As it can be seen that memory at CS:IP contains lots of 'FF's, that exception isn't a big surprise. Regretably, it's also not a big help.

**Comment by vanfanel** [comment]
> > What's exception 06? Does it ring any bells?
> 
> Well, it's an "invalid opcode" exception. As it can be seen that memory at CS:IP contains lots of 'FF's, that exception isn't a big surprise. Regretably, the dump isn't a big help either in this case.

Is there a way to somehow isolate that memory area so JEMMEX doesn't use it or something like that?

**Comment by Baron-von-Riedesel** [comment]
> is there a way to somehow isolate that memory area so JEMMEX doesn't use it or something like that?

The problem here is that the crash itself doesn't give any hint about what the real problem is.

What I can see, though, is that this is not the current version of JemmEx - because register CR2 is displayed, while the current JemmEx should display the contents of register CR4. Just mention that, I don't think that it makes any difference.

**Comment by Baron-von-Riedesel** [comment]
> the crash happens when I move the mouse around: if I don't move the mouse, I never get the crash!

So it might be a problem with IRQs or stacks. And how's the mouse connected? PS/2, USB or Serial?

**Comment by vanfanel** [comment]
I have several systems running JEMMEX. In all of them, mouse is connected on USB using PS/2 emulation.
For example, the Tinyllama v2 uses hardware USB HID (keyboard+mouse) to PS/2 emulation using [rasteri's HIDman firmware](https://github.com/rasteri/HIDman) running on a CH559 microcontroller

**Comment by vanfanel** [comment]
> > I also have several laptops running FreeDOS ...
> 
> IMO the first step is to use MS-DOS instead of FD to avoid any possible incompatibilities.

You were totally right on this. With MS-DOS, the game runs perfectly well!
