### ISSUE TITLE
Some programs crash when EMS disabled (NOEMS) but work fine when EMS enabled (RAM).

### ISSUE THREAD

**Issue by lss4** [Baron-von-Riedesel/Jemm#26]
I don't know if there were similar reports in the past but I noticed something interesting.

Some games would crash (e.g. fail to start with unexpected errors) when JEMM is started without EMS (`NOEMS`), but work without issues when EMS is enabled (`RAM`). Since EMS reserves 64KB of upper memory, the latter is only feasible when the system has enough usable UMB areas for other TSRs.

Notable examples are those that use Borland 16-bit RTM, like Jazz Jackrabbit and Tyrian 2000. HDPMI16 is required for those games to start properly if EMS disabled, but not needed if EMS enabled.

This is observed on PC-DOS 7.10. In this case, I'm using separate DOS startup configurations, with starting JEMM (JEMMEX) using `NOEMS` or `RAM` being the only difference.

(EDIT: Just did some tests in FreeDOS and could reproduce the same behavior. When EMS is enabled, games in question can start fine without the need of HDPMI16.)

The other arguments I used for JEMM were mostly based on a vanilla FreeDOS default and customized from there.
`I=TEST X=TEST I=B000-B7FF VME SPLIT`

AFAICT these arguments, as long as they don't impede DOS' ability to start properly, have little impact on this particular issue. Games in question would crash regardless of other arguments used for JEMM (be it JEMMEX or JEMM386 with another XMS manager), so long as it's started with `NOEMS`.

I'm currently using the most recent (5.84) version of JEMM, but I think the problem existed for quite a while...

**Comment by Baron-von-Riedesel** [comment]
I didn't notice any difference regarding tyrian/jazz if I run Jemm with EMS enabled or not. In both cases, tyrian starts without problems, while Jazz throws runtime error 200. I'm using MS-DOS 7.1.

So this doesn't seem to be a generic problem...

**Comment by lss4** [comment]
I'm currently testing this on a X99-based motherboard. My current system config allows access to about 141KB of upper memory (including B000-B7FF) and can reasonably set up a EMS page frame at D800, making `RAM` a viable startup option.

Tested with MS-DOS 7.1 kernel and in most cases only Jazz as a reference, since many aspects are shared among games that use Borland RTM.

When I loaded JEMMEX with `NOEMS`, games in question (Jazz/Tyrian) always crashes on first two runs with the following error:
```
Unhandled exception 000E at 0020 1A9E ErrCode 0002
```
The first two exceptions are always `000E` though the address may vary depending on TSRs loaded. On third and subsequent runs things become different.

If there are no big TSRs present in the UMB, these games (Jazz/Tyrian) will be able to actually start without issues on third and subsequent runs. The run count is shared by all RTM games, so after I successfully ran Jazz I can then start Tyrian without having to deal with the first two `000E` crashes.

If there is something relatively big loaded in the TSR, depending on the TSRs loaded Jazz will still not run and will exhibit varying behaviors including but not limited to:

1. A simple `0006` exception, ErrCode `0000` output saying `Loader error (0006): unexpected error`.
2. In Jazz's case, third run gives `Internal error 0023  (gibberish)o initialize page tablesesr`, then subsequent runs behave the same as 1.
3. A HUGE `UNHANDLED EXCEPTION 06 at 00E7:8A04 Error code: 0000` output (with register states and such, offering options to terminate current process or all, address may vary depending on config). I only encountered it once, and back then I issued D to terminate all, and subsequent runs give me `Loader error (0025): cannot initialize.`
4. Reboots on third run.

Additionally, I just tried starting JEMM `NOEMS` with the region that otherwise would become EMS page frame reserved (`X=D800-E7FF`) and it did not make any difference.

It feels like DOS is a bit more unstable when `NOEMS` is used instead of `RAM`. I'm currently looking mostly at RTM at the moment as it's the most sensitive and the erratic behaviors are easiest to reproduce.

From what I could remember, running `HDPMI16` fixes most if not all problems regarding launching those games in a `NOEMS` config, while on this particular system, `HDPMI16` is not required and those games can start without any issue when using a `RAM` config, though `HDPMI16` may still be a bit helpful.

PS: Does JEMM's `NOEMS` really disable expanded memory? Actually, when using `NOEMS`, `MEM` still reports about having 8MB of "Expanded" (not "Extended") memory.

**Comment by Baron-von-Riedesel** [comment]
> PS: Does JEMM's NOEMS really disable expanded memory? Actually, when using NOEMS, MEM still
> reports about having 8MB of "Expanded" (not "Extended") memory.

Yes, that's true. I guess this is done because MS Emm386 does it as well.

> The first two exceptions are always 000E though the address may vary depending on TSRs loaded. On third and subsequent 

This is a pretty good indication that the status has changed. Use the VCPI.EXE tool supplied with Jemm and see if the number of free VCPI pages may have changed after your first and second try.

**Comment by lss4** [comment]
> This is a pretty good indication that the status has changed. Use the VCPI.EXE tool supplied with Jemm and see if the number of free VCPI pages may have changed after your first and second try.

Can confirm. When using default values for VCPI, with currently configured TSRs, the free 4K pages across runs are:
Before first: 30711 (122844 kB)
First run: 14561 (58244 kB)
Second run and onwards: 310 (1240 kB)

> Generally, Jemm's default for VCPI memory is 128 MB - IIRC best for compatibility with Borland is to reduce it to 31 MB - use the MAX option for that.

Yeah, after setting this to 31MB or less, games in question can run without issues.

It's possible such games consume a good amount of 4K pages without releasing them when they crashed this way, and after two runs the free page count drops to an amount below 31MB. If there were just enough pages for them to run everything would be good, but depending on configuration it's entirely possible to have a free page count too low for them to start which results in a different error.

However, it seems setting this limit breaks either JLOAD or AHCICD, as I'm getting this exception and the system subsequently freezes after I press ESC, when it's being loaded.

(Singled out via step-on-step confirmation, as after skipping only JLOAD, everything else loaded fine.)

```
JemmEx: Exception 0D occurred at CS:EIP=0008:F84000BA, ERRC=000089C0
SS:ESP=0010:0000263C EBP=00002614 EFL=00013047 CR0=80000013 CR4=00000649
EAX=00115000 EBX=000040D4 ECX=00003F28 EDX=00000000 ESI=00111474 EDI=00000000
```

**Comment by Baron-von-Riedesel** [comment]
In Jemm's Readme there's a "Hints & Troubleshooting" chapter. Among others, it already covers the problems with Borland's extender.

> However, it seems setting this limit breaks either JLOAD or AHCICD.DLL, as I'm getting this exception and the system 

Will see if I can reproduce this error - the address already tells that the fault happens in jload.

**Comment by lss4** [comment]
An update on this...

As for the JLOAD error, it was probably due a configuration mistake as I didn't know what unit `MAX` uses by default, so I didn't specify one... I specified `MAX=31` thinking it would be 31MB. Changing this to `MAX=32752K` as said in the manual fixed it. Now both JLOAD and RTM work fine.

On the other hand, does specifying `RAM` (enable EMS) automatically limits VCPI to below 32MB since that's the default amount of EMS?

I don't know if there are already good use cases of a high amount of VCPI memory like 128M. Perhaps using 32752K as default would make JEMM more compatible with existing software that were known to be troublesome.

Since this issue is already known and documented, and workarounds available, I'm closing this as completed.
