### ISSUE TITLE
UMB does not get enabled on EDR-DOS (single-file load)

### ISSUE THREAD

**Issue by lss4** [Baron-von-Riedesel/Jemm#27]
When booting to the recent single-file load version of Enhanced DR-DOS kernel (EDRDOS.COM), neither `NOEMS` nor `RAM` of JEMM enables UMB. Other functionalities of JEMM still works, however.

FreeDOS `MEM /D` says UMB is not accessible, and all TSRs are loaded to conventional memory.

I'm booting EDR-DOS with lDebug, and am using FreeDOS' utilities for the rest of the DOS functionalities, including COMMAND.COM. I'm using JEMMEX as I'm not using another XMS manager, and I'm using the same arguments I used when booting other DOS kernels (`I=TEST X=TEST I=B000-B7FF VME SPLIT`).

I'm still new to EDR-DOS so I'm not sure if I need to do something specific to EDR-DOS in order to use UMB, or there are some issues either on JEMM or EDR-DOS side. Maybe @ecm-pushbx can help out?

**Comment by ecm-pushbx** [comment]
You have `dos=umb` in [d]config.sys, right? Is it before or after the `device=` line for JemmEx?

**Comment by lss4** [comment]
> You have `dos=umb` in [d]config.sys, right? Is it before or after the `device=` line for JemmEx?

Thanks for the reply. I originally specified `DOS=HIGH,UMB` at the beginning of DCONFIG.SYS, before all `DEVICE` directives. That's how I usually do on other DOS kernels (MS-DOS, PC-DOS, FreeDOS).

It seems EDR-DOS expects `DOS=UMB` to be declared **after** loading JEMM (JEMMEX) in order to be able to use UMB. After I moved `DOS=UMB` after the JEMMEX line, UMB now works as expected. I wonder if this is an intended behavior for EDR-DOS.

**Comment by ecm-pushbx** [comment]
It appears to be intended, yes. I've heard of this behaviour before.

**Comment by lss4** [comment]
Okay. Thank you for clarifying. :-)

Closing the issue.
