### ISSUE TITLE
Jemm386 crashes on real machine

### ISSUE THREAD

**Issue by fritzmueller** [Baron-von-Riedesel/Jemm#4]
I beg your pardon, but it is easier to write in german for me:
Ich habe eine Startdiskette mit jemm386 gebaut, läuft soweit gut, allerdings gibt es Probleme, wenn ich xkeyb gr.key aufrufe: (Grund für xkeyb ist, daß mkeyb in virtualbox z und y vertauscht, auch bei mkeyb gr, unter vmware läuft das einwandfrei).
a) wenn ich die Startdiskette in virtualbox aufrufe, wird der deutsche Tastaturtreiber geladen,
b) wenn ich die Startdiskette auf einer echten Maschine aufrufe, passiert erst mal nichts, tippe ich aber "zz" ein, um die Tastatur zu testen, wird das erste "z" noch geschrieben, dann passiert eine Zeitlang nichts, dann erhalte ich die Meldung:
Jemm386: exception 06 occured at CS:EIP=073D:00002ABD, ERRC=00000000
SS:ESP=14AA:000001CAC EBP=00001CD4 EFL=00033202 CR0=80000013 CR2=000 ???
EAX=044F077A EBX=00003156 ECX=00001CCE EDX=00000001 ESI=00001CD2 EDI=
Press ESC to abort program
dos mem corrupt, first_mcb=0540
prev 0000:0000|bf usw
notMZ0540:0000|00 usw

PANIC: MCB chain corrupted,
System halted

die Werte scheinen nicht immer identisch zu sein. 
Ich werde jetzt mal die neueste preview testen.

**Comment by fritzmueller** [comment]
Ok, ich habe mich mal ein bischen gespielt und eine FreeDOS iso-Datei erstellt und eine CD gebrannt.
Unter vmware und virtualbox laufen
[FreeDOS08c.zip](https://github.com/Baron-von-Riedesel/Jemm/files/4432232/FreeDOS08c.zip)

 die iso-Datei und die CD einwandfrei, sowohl mit jemmex und jemm386.
Wenn ich die CD allerdings vom PC starte (an zwei PCs getestet), stürzt jemm386 ab, sobald ich (lh) xkeyb gr.key eingebe.

**Comment by fritzmueller** [comment]
So, ich habe jetzt mal den neuesten himemx in meine Startdiskette hineinkopiert. Außerdem wurde xkeyb 1.50 durch 1.15 ersetzt (das ist trotz kleinerer Nummer die neueste Version. Seitdem läuft xkeyb gr ohne Probleme, sowohl in der vm als auch auf echten Computern.
Vielen Dank!

**Comment by fritzmueller** [comment]
jemmex 5.80 arbeitet anscheinend nicht mit tree zusammen. Zumindestens in virtualbox.

Ich erhalte eine exception 0D vgl. Anlage.

 

Gruß

 

W. Spiegl / Fritz

 

 

 
 

Sent: Thursday, October 29, 2020 at 6:31 AM

**Comment by Baron-von-Riedesel** [comment]
Sehe leider keine Anlage.
Benötige auch aufruf von jemmex in config.sys, um die aktuellen Optionen zu sehen.

**Comment by fritzmueller** [comment]
Ich habe gerade nachgeschaut, die Anlage war dabei, wurde von github anscheinend weggelassen.
Wenn Ihnen meine Testmaschine für virtual box genügt, bei der ich das festgestellt habe, die wäre hier:

https://my.hidrive.com/lnk/rzI1OyaY

incl. fast fertiger Hilfe.

Gruss

W. Spiegl / Fritz

**Comment by Baron-von-Riedesel** [comment]
Ok, have vbox installiert und die "appliance" importiert.
FreeDOS startet, das Menu beende ich mit Alt-X, dann gebe ich ein
C:\>tree<enter>
und es wird der Verzeichnisbaum ausgegeben.
Keine Exception soweit. Was muß ich tun?

**Comment by fritzmueller** [comment]
Gute Frage, ich habe es soeben bei mir nochmals ausprobiert und es gibt momentan keine Probleme. Ich kann Ihnen nur nochmal den Screenshot schicken oder die Ausgabe abtippen.

 

Das Problem, das ich habe, ist, daß die help.exe diverse Probleme macht, teilweise auch mit jemm386. Auch dazu hätte ich Screenshots.

 

Eine der Sachen mit Help.exe ist, daß man mit der Pfeiltaste nach unten gehen kann und unten links plötzlich Links angezeigt werden, die es nicht gibt (wirre Zeichen oder Links, auf die vom einzelnen htm file aus nicht verlinkt wird, das ist unterschiedlich). Wenn man das oft genug und mit verschiedenen Dateien macht, kommt auch dort die jemmex-Fehlermeldung.

 

Die Screenshots sind hier ganz sicher dabei, falls sie nicht ankommen, hier sind sie nochmal:

 

https://my.hidrive.com/lnk/LroVObzi

 

Gruß

 

W. Spiegl

 

 
 

Sent: Thursday, November 19, 2020 at 3:51 PM

**Comment by Baron-von-Riedesel** [comment]
Die screenshots habe ich. Nur kann man damit nicht viel anfangen. Wenn jemm einen Fehler meldet, läuft das Programm normalerweise bereits Amok, die eigentliche Fehlerursache kann man so nicht erkennen.
Im screenshot "Tree-exception.jpg" ist dummerweise der Inhalt von Register EDI nicht zu sehen (vermutlich 0000ffff, weil nur das ein GPF beim aktuellen opcode verursachen kann), aber selbst wenn man's sehen könnte, bringt einen das nicht weiter.

Das Einzige was evtl. hilft ist I=TEST hinter jemmex.exe zu entfernen, bzw. x=c000-efff einzufügen.

**Comment by fritzmueller** [comment]
Der Tree-Fehler ist gelöst. Der Grund, warum auch immer ist die tree.de Datei. Dort habe ich oben den Kommentar:

 

#Codepage 850/858  ergänzt, gefolgt von einer Leerzeile und dann

 

1.1\n usw.

 

eingegeben. Diese Zeile führt zum JEMM-Hänger. Wenn ich die Leerzeile dazwischen rausnehme, funktioniert alles wieder.

Ich bitte vielmals um Entschuldigung. Bei allen anderen NLS gab es diesbezüglich keine Probleme.

 

Ich wäre Ihnen aber sehr dankbar, wenn Sie eventuell die Probleme mit help.exe wenigstens kurz überprüfen könnten.

Mir wäre schon geholfen, wenn ich dem FreeDOS-Team mitteilen könnte, daß help wirklich buggy ist. Leider bin ich kein

Programmierer.

Es sind derart viele Probleme mit dieser help.exe, daß ich schon darüber nachdenke, ob die Verwendung von Arachne nicht eventuell sinnvoller wäre.

Allein schon eine fehlende UTF-8-Unterstützung hat mich an den Rand des Wahnsinns gebracht, weil ein Kollege die Übersetzung mit der falschen

Codepage geliefert hatte und nicht wußte, welche er überhaupt verwendet hat. Und französisch / spanisch mit seinen vielen Accents macht es dann

nicht leichter.

 

Vielen Dank

 

W. Spiegl

 
 

Sent: Thursday, November 19, 2020 at 6:11 PM

**Comment by Baron-von-Riedesel** [comment]
> Ich wäre Ihnen aber sehr dankbar, wenn Sie eventuell die Probleme mit help.exe wenigstens kurz überprüfen könnten.

Also ich kann keine gravierenden Fehler mit help entdecken. Abstürze mit JemmEx Fehlermeldungen bekomme ich schon gar nicht hin.

**Comment by fritzmueller** [comment]
Trotzdem vielen Dank. 

W. Spiegl
