### ISSUE TITLE
Jemmex crashing when opening a DOS/4G application in DOSBox-X

### ISSUE THREAD

**Issue by JayQ2K** [Baron-von-Riedesel/Jemm#8]
Today, within a DOSBox-X 0.83.10 environment, I tried to run an application that requires DOS/4G. It immediately crashes.

Environment and parameters:
DOSBox-X 0.83.10
JEMMEX 5.79B; Jemmex.exe loaded without any command line switches
DOS/4G 2.01

The received error is like below.
![command_001](https://user-images.githubusercontent.com/63723599/108603136-73d47180-73a6-11eb-92b8-2e60a548205a.png)

Seems like the handover from Jemmex to DOS/4G is not working correctly. Is this related (indirectly I guess) to the GEMMIS issue that is opened? It might be another specification, but when using EMM386.exe (v4.49 of v4.95) I am launched into the application succesfully.

**Comment by Baron-von-Riedesel** [comment]
> Is this related (indirectly I guess) to the GEMMIS issue that is opened?

No, that's a Win3x issue.
Exception 0E is a page fault. That should never happen in v86-mode. What is opcode FE 38 42 00 ?
I'm pretty sure this is an issue that happens with DOSbox only - and using Jemm inside DOSBox is "unsupported".

**Comment by JayQ2K** [comment]
So I figured this one out. Typical case of one thinking they know more than the README.
X=TEST or X=C400-C4FF is very much required for DOS/4G applications to function under DOSBox-X with Jemmex. The other 2 troubleshooting parameters (NOHI, NOINVLPG) I can so far do without for DOS/4G applications.
Launching with the VERBOSE switch I can see the following difference that is probably relevant here:
1. Memory map > the first 4kB block after the EPROM at c000, 16kB changes from U to X
- c0000: EEEE**U**UUUUUUUUUUU becomes EEEE**X**UUUUUUUUUUU

Including NOTEST.TXT and YESTEST.TXT where the latter is the one with X=TEST parameter included
[NOTEST.TXT](https://github.com/Baron-von-Riedesel/Jemm/files/6017637/NOTEST.TXT)
[YESTEST.TXT](https://github.com/Baron-von-Riedesel/Jemm/files/6017638/YESTEST.TXT)
The differences between the files show up in the XMSSTAT part.

Probably means that EMM386.exe excludes that space by default. And DOS/4G probably just tries the first available U block when launching.
Is there something fishy about that C400 block and is it disabled by default by other V86 monitors?

**Comment by JayQ2K** [comment]
Microsoft System Diagnostics (MSD.EXE, Version 2.11 or 3.01) for DOS shows that under EMM386 the whole range C400-CBFF is excluded as addressable space.

**Comment by JayQ2K** [comment]
I'll be closing this case since it's clear what is happening. Maybe the following is something for the README:

 7. Troubleshooting, Hints

 þ Using JEMM with the Internal XMM provider (xms=true) from DOSBox:
The below has nothing to do with Jemm, but in case problems arise when using this specific configuration the following is proposed to remediate.
v5.79: Always use at least X=TEST or for full safety X=A000-FFFF when using Jemm inside DOSBox with the Internal XMS provider. Specifically DOS/4G applications will crash the whole machine instance without this switch set.

v5.80 (pre7 and up): With the scanning of C000-EFFF activated again, all UMB seems to lock when using the Internal XMS provider. Use I=CC00-EFFF to get a good amount of EMS for the page frame and high loading of device drivers.

**Comment by JayQ2K** [comment]
To add to the previous remark is that the scanning re-activation of C000-EFFF all UMB that was unlocked under 5.79 remains locked under 5.80.
So this scanning might also be the way to getting the internal XMM behave as planned. I'll be working that out with DOSBox team.
